### ISSUE TITLE
could not find function "valid_udunits"

### ISSUE THREAD

**Issue by piiskop** [graphdr/formatdown#1]
```
librarian::shelf(c(
  "formatdown"
))
a <- c(123.456, 2e-6, 5e8, 0.23)
units(a) <- "km"
format_units(x=a, unit="ydard")
```

results with 

> 
> Error: In ‘ydard’, ‘ydard’ is not recognized by udunits.
> 
> See a table of valid unit symbols and names with valid_udunits().
> Custom user-defined units can be added with install_unit().
> 
> See a table of valid unit prefixes with valid_udunits_prefixes().
> Prefixes will automatically work with any user-defined unit.

`valid_udunits()`

results with

> Error in valid_udunits() : could not find function "valid_udunits"

**Comment by graphdr** [comment]
I wonder if you meant to use the units of "yard", not "ydard"?

**Comment by piiskop** [comment]
You are right. What a mistake that I made!
