### ISSUE TITLE
"format_power": "digits" does not resemble significant digits.

### ISSUE THREAD

**Issue by piiskop** [graphdr/formatdown#2]
```
librarian::shelf(c(
  "formatdown"
))
numbers <- c(123.456, 2e-6, 5e8, 0.23)
format_power_numbers <- format_power(numbers)
format_power_numbers_digits <- format_power(numbers, digits = 2)
```

Real output:

> [1] "$123 \\times 10^{0}$"  "$2.0 \\times 10^{-6}$" "$500 \\times 10^{6}$"  "$0.23$"        

Expected output:

> [1] "$120$"  "$2.0 \\times 10^{-6}$" "$500 \\times 10^{6}$"  "$0.23$"               

Or at least:

> [1] "$120 \\times 10^{0}$"  "$2.0 \\times 10^{-6}$" "$500 \\times 10^{6}$"  "$0.23$"               

We should also distinguish the number of significant digits in different cases: whether there is a multiplication or addition.

**Comment by graphdr** [comment]
Digits in `format_power()` are determined using `formatC()` with `format = 'fg'`, which uses fixed format but displays the _minimum number of significant digits_. This can lead to quite long result strings, unlike `signif()`. You can take a look at `? formatC()` for more detail. 

This was an arbitrary choice and I could possibly add an argument that allows the user to use `signif()` (for example) which would yield the anwers you prefer.

**Comment by piiskop** [comment]
How should we understand the explanation for _digits_:

> Numeric scalar, 

> significant digits in coefficient, integer between 1 and 20.

It tells us something about significant digits and nothing about the minimum number of significant digits. What should be between 1 and 20, the scalar value or the number of significant digits or the coefficient?

**Comment by graphdr** [comment]
Between 1 and 20 means you are permitted between 1 significant digit and 20 significant digits. The "minimum number of significant digits" description is from the `formatC()` help page. `formatC()` is the R function used in formatdown to convert the numerical values in one's vector to character strings.  

However, in the current development version, I have internally added the use of `sigfig()` before applying `formatC()` to produce the expected output you describe earlier.  

That was quite useful feedback. Thanks. 

If your download the development version (I'll upload it in the next hour or so) and give it a try, i think I've addressed the issues your raised.

**Comment by graphdr** [comment]
Development version is now on GitHub

**Comment by piiskop** [comment]
The third value still is not 5.0 times whatever but is 500 times whatever.

**Comment by graphdr** [comment]
The default is engineering format (where all exponents are multiples of three). The following are equivalent: 
`format_power(numbers, digits = 2)`
`format_power(numbers, format = "engr", digits = 2)`

To get 5.0 times etc., set the format to "sci", for example, 
`format_power(numbers, format = "sci", digits = 2)`

**Comment by piiskop** [comment]
I did what you told me to do - added the scientific format. However, it does not work. It only worked for that particular number. It does not work on 0.23 or 123.456. Yes, two significant numbers remain but the format is not scientific.

**Comment by graphdr** [comment]
Try setting omit_power = NULL

**Comment by piiskop** [comment]
With `omit_power=NULL` the scientific notation seems to work.
