### ISSUE TITLE
very small numbers not formatted with exponent.

### ISSUE THREAD

**Issue by stanstrup** [graphdr/formatdown#5]
`format_power(2e-15, 2, format = "sci")`
[1] "$2.0 \\times 10^{-15}$"

`format_power(2e-16, 2, format = "sci")`

[1] "$0.00000000000000020$"

**Comment by graphdr** [comment]
I've reproduced your example and get the same error. I'll dig into the code to figure out what's going on. I think it has to do with the machine double eps. 

Yes, that was it. Error has been corrected and will be posted asap.

**Comment by graphdr** [comment]
I think it has to do with the machine double eps.

**Comment by graphdr** [comment]
Correction will appear in next release.

**Comment by stanstrup** [comment]
Super. Thanks!

**Comment by graphdr** [comment]
The current development version includes this correction. You can download it from GitHub if you want to. Thanks for the issue!
