### ISSUE TITLE
"format_power" cannot be used with some units.

### ISSUE THREAD

**Issue by piiskop** [graphdr/formatdown#7]
```
librarian::shelf(c(
  "formatdown"
))
G <- 6.67384e-11
units(G) <- "m3 kg-1 s-2"
format_power(x=G)
```

> Error: ‘`m`^(3)`.kg`^(-1)`.s`^(-2)’ is not a unit recognized by udunits or a user-defined unit

**Comment by graphdr** [comment]
I show an example of applying the power-of-ten notation to a value of class "units" on the format_units() vignette.  In your case, it would go something like this, 

```
# Start with a numeric value
G <- 6.67384e-11

# Do some units things
display_units <- "m3 kg-1 s-2"
units(G) <- display_units

# Convert back to numeric to power formatting
G <- format_power(as.numeric(G))

# Paste the display units to the result
G <- paste0(G, " [", display_units, "]")

# View the result
G
#> [1] "$66.74 \\times 10^{-12}$ [m3 kg-1 s-2]"
```

All the workaround is because format_power() isn't set up to handle the units class.  But it should be a really easy fix to add that capability to the next dev version.

**Comment by piiskop** [comment]
Is there a way to use the output as input for _siunitx_? The output like that is not edible for _siunitx_. Its _qty_ expects an input like 66.74e-12 and does not eat "\times". Units as displayed in the output are also not edible to its _unit_. So if using _formatdown_, I still have to enter units manually.

**Comment by graphdr** [comment]
In the development version 0.1.3.9001, I've introduced an updated set of formatting functions that seem to handle the units OK. You can download this version from GitHub. When I've completed the examples and units tests, I'll release a new version to CRAN. 

To use your example, 

    G <- 6.67384e-11
    units(G) <- "m3 kg-1 s-2"
    format_numbers(G)

the output is `"$66.74 \\times 10^{-12}\\>\\mathrm{m^{3}\\>kg^{-1}\\>s^{-2}}$"`

which renders as:

$66.74 \\times 10^{-12}\\>\\mathrm{m^{3}\\>kg^{-1}\\>s^{-2}}$

If you prefer scientific notation, you can use `format_sci(G)`, which yields, 

$6.674 \\times 10^{-11}\\>\\mathrm{m^{3}\\>kg^{-1}\\>s^{-2}}$

**Comment by graphdr** [comment]
Regarding your question about _siunitx_, I designed formatdown for R Markdown or Quarto Markdown documents rather than as input to a LaTeX package.

**Comment by graphdr** [comment]
Version 0.1.4 has posted to CRAN and renders your example correctly.
