### ISSUE TITLE
Degree Celsius and micron in PDF

### ISSUE THREAD

**Issue by JayOBee** [graphdr/formatdown#8]
Great little package, thanks! 

I found that for some specific units, the pdf output from R markdown does not work properly, namely °C and µm. 
Here’s a MWE of a `.Rmd` file:

``` 
```{r}
library(units)
library(formatdown)
x <- 10
y <- 10
units(x) <- "µm"
units(y) <- "degree_C" ``` 
Length is `r format_numbers(x)`, temperature is `r format_numbers(y)`
```

I am assuming that similar units display the same behaviour (e.g. µs or °F, haven’t tried ohm out). 

From what I found in the PdfTeX logfile, it appears that somewhere in the knit process, a `µ` is converted to a `\textmu` and a `°` is converted to a `\textdegree` and that does not work in math mode: 

```
LaTeX Warning: Command \textmu invalid in math mode on input line 132.
...
LaTeX Warning: Command \textdegree invalid in math mode on input line 132.
``` 

I’ve created this wrapper function as a hacky fix: 
```
format_numbers2 <- function(...) {
  x <- format_numbers(...)
  x <- gsub("µ", "\\\\text{µ}", x)
  x <- gsub("°", "\\\\text{°}", x)
  return(x)
}
```

I’m using R 4.4.1 and the dev version of formatdown (0.1.4.9002).

**Comment by graphdr** [comment]
Thanks for the note. Odd that math mode works fine in HTML output but not in PDF output. Good work on identifying the problem. I'll have to explore this to find out which units exhibit this behavior. 

You might also check out the "gt" R package for formatting numbers with units and powers of ten (a package from POSIT). Quite extensive.

**Comment by graphdr** [comment]
Per this [link](https://bookdown.org/yihui/rmarkdown-cookbook/latex-unicode.html), this error can occur when we use the default LaTeX engine, pdflatex. You may switch to xelatex or lualatex in the Rmd header, e.g., 

```
output:
  pdf_document:
    latex_engine: xelatex
```

This seems to solve the problem.  I ran examples using Ω, °R, °F, Å, µm, etc. and the document seems to render OK in both PDF and HTML.

**Comment by JayOBee** [comment]
Thanks for taking a look! That solves the issue!
